-- Subscriptions and Upload Usage tables have been consolidated into 004_profiles.sql 
-- to ensure they exist before the handle_new_user trigger is created.
-- This file is kept for migration history consistency but is now empty.
